version: "3.5"

services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - default

networks:
    default:
        name: localnet
        external: true
