version: "3.5"
services:
    redis:
        image: redis:5.0.7
        restart: always
        command: ["redis-server", "--appendonly", "yes"]
        ports:
            - '6379:6379'
        networks:
            - default

networks:
    default:
        name: localnet
        external: true
