version: "3.5"
services:
    redis:
        image: redis:5.0.7
        restart: always
        command: ["redis-server", "--appendonly", "yes"]
        ports:
            - '6379:6379'
        networks: &networks
            - default

    mongodb:
        image: mongo
        restart: always
        networks: *networks
        ports:
            - "27017:27017"

    rabbitmq:
        image: rabbitmq:3-management-alpine
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        networks: *networks

    mysql:
        image: mariadb:10.1
        container_name: mysql
        restart: always
        command: --max_allowed_packet=2G --character_set_server=utf8 --collation_server=utf8_general_ci
        networks: *networks
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - ./db_folders/mysql:/var/lib/mysql
            - ./userfolder/mysql:/etc/mysql/conf.d

networks:
    default:
        name: localnet
        external: true
